version: '3.8'

services:
  osrm-backend:
    image: osrm/osrm-backend
    container_name: osrm-backend
    volumes:
      - ./data:/data
    command: >
      sh -c "
      if [ ! -f /data/indonesia-latest.osrm ]; then
        osrm-extract -p /opt/car.lua /data/indonesia-latest.osm.pbf && \
        osrm-partition /data/indonesia-latest.osrm && \
        osrm-customize /data/indonesia-latest.osrm;
      fi && \
      osrm-routed --algorithm mld --threads 24 /data/indonesia-latest.osrm
      "
    ports:
      - "5000:5000"
    restart: unless-stopped