version: '3.8'

services:
  osrm-backend:
    image: osrm/osrm-backend
    container_name: osrm-backend
    volumes:
      - ./data:/data
    command: >
      sh -c "
      if [ ! -f /data/indonesia-latest.osrm ]; then
        osrm-extract -p /opt/car.lua /data/indonesia-latest.osm.pbf && \
        osrm-partition /data/indonesia-latest.osrm && \
        osrm-customize /data/indonesia-latest.osrm;
      fi && \
      osrm-routed --algorithm mld --threads 24 --ip 0.0.0.0 /data/indonesia-latest.osrm
      "
    ports:
      - "5000:5000"
    restart: unless-stopped

  osrm-frontend:
    image: osrm/osrm-frontend
    container_name: osrm-frontend
    environment:
      - OSRM_BACKEND=http://192.168.50.100:5000
    ports:
      - "9966:9966"
    restart: unless-stopped

  nominatim:
    image: mediagis/nominatim:4.4
    container_name: nominatim
    volumes:
      - ./nominatim-data:/nominatim/data
    environment:
      - PBF_PATH=/nominatim/data/indonesia-latest.osm.pbf
      - THREADS=16
      - IMPORT_STYLE=full
    ports:
      - "8080:8080"
    restart: unless-stopped
